# Shell prompt
function ssh_slug {
    if [ "$SSH_CONNECTION" ]; then
        echo $(whoami)@$(hostname)
    fi
}
function git_slug {
    # test git repo
    if git status --porcelain &>/dev/null; then
        # abbreviated branch or tag name
        echo -n "$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
        # asterisk if repo dirty
        if [ -z "$(git status --porcelain)" ]; then
            echo "  "
        else
            echo "* "
        fi
    fi
}
export PS1='$(ssh_slug) \[\033[1;33m\]\w\[\033[0m\] $(git_slug)$ '

alias l="LC_COLLATE=C ls --group-directories-first -FHAlh -w 80"
alias ll="LC_COLLATE=C ls --group-directories-first -FHA -w 80"
alias ls="LC_COLLATE=C ls --group-directories-first -FH -w 80"

shopt -s cmdhist
shopt -s histappend
shopt -s checkwinsize
shopt -s extglob
shopt -s globstar
shopt -s checkjobs

export PATH=$HOME/.local/bin:$PATH
