cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'ack'
brew 'antigen'
brew 'atool'
brew 'awscli'
brew 'blueutil'
brew 'cabal-install'
brew 'coreutils'
brew 'curl'
brew 'dict'
brew 'diction'
brew 'ffmpeg'
brew 'gdb'
brew 'git'
brew 'gnupg'
brew 'grep'
brew 'htop'
brew 'imagemagick'
brew 'jq'
brew 'make'
brew 'mas'
brew 'newsboat'
brew 'p7zip'
brew 'pandoc'
brew 'pass'
brew 'poppler'
brew 'python'
brew 'python3'
brew 'r'
brew 'rsync'
brew 'ruby'
brew 'ssh-copy-id'
brew 'trash'
brew 'tree'
brew 'unrar'
brew 'vim'
brew 'w3m'
brew 'watch'
brew 'wget'
brew 'xz'
brew 'youtube-dl'
brew 'zsh'

cask 'alfred'
cask 'backblaze'
cask 'calibre'
cask 'caskroom/versions/firefox-beta'
cask 'caskroom/versions/java8'
cask 'clamxav'
cask 'fantastical'
cask 'gimp'
cask 'grandperspective'
cask 'iterm2'
cask 'java'
cask 'java-jdk-javadoc'
cask 'mactex'
cask 'microsoft-office'
cask 'musescore'
cask 'omnifocus'
cask 'omnigraffle'
cask 'omnioutliner'
cask 'scapple'
cask 'scrivener'
cask 'textual'
cask 'torbrowser'
cask 'transmission'
cask 'tunnelblick'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'

brew 'maven'

cask 'caskroom/fonts/font-anonymous-pro'
cask 'caskroom/fonts/font-inconsolata'
cask 'caskroom/fonts/font-roboto-mono'

# mas 'macOS High Sierra', id: 1246284741
mas 'Xcode', id: 497799835
