#!/usr/bin/env bash

udisksctl unlock \
    --block-device /dev/sdb \
    --key-file <(pass drives/expansion | head -n 1 | tr -d '\n')
udisksctl mount --block-device /dev/sdb
echo "TODO: update block device to be more specific"
