#!/usr/bin/env bash

sudo -v
udisksctl unmount -b /dev/mapper/expansion # unmount device
# TODO do `udisksctl lock -b /dev/sdb` once `expansion-mount` can use `udisksctl unlock`
sudo cryptsetup close expansion # close device
udisksctl power-off -b /dev/sdb
