#!/usr/bin/env bash

sudo -v
udisksctl unmount -b /dev/mapper/expansion # unmount device
# TODO Use udisksctl lock -b /dev/sdb
sudo cryptsetup close expansion # close device
udisksctl power-off -b /dev/sdb
