#!/usr/bin/env bash

# Update dotfiles
git -C "$HOME/dotfiles" pull

# Update submodules
git -C "$HOME/dotfiles" submodule foreach git pull

# Upgrade system
sudo nixos-rebuild switch --upgrade

# Upgrade home
home-manager switch

# Upgrade Neovim plugins
nvim +PlugUpgrade +PlugUpdate +PlugClean +qall

# Imperatively set some config options
kwriteconfig5 --group RecentDocuments --key UseRecent false
