#!/usr/bin/env bash

# TODO Install urxvt-resize-font

if [[ "$OSTYPE" =~  linux* ]]
then
    echo "Linux operating system confirmed."
else
    echo "Operating system not Linux. Aborting."
    exit 1
fi

if [ -f "/etc/debian_version" ]
then
    echo "Debian distribution confirmed."
else
    echo "Distribution not Debian. Aborting."
    exit 1
fi

echo "Testing Internet connection..."
if ping -c 1 google.com >& /dev/null
then
    echo "Internet connection successful."
else
    echo "Internet connection failed. Aborting."
    exit 1
fi

# Authenticate user upfront
sudo -v

# Use apt-get
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get autoremove
sudo apt-get clean
sudo apt-get check

# TODO Create directory tree.txt skeleton

# Generate SSH key pair
mkdir "$HOME/.ssh"
if ! [ -e "$HOME/.ssh/id_rsa" ]
then
    echo "Generating SSH key..."
    read -p "Enter a unique name for your key: " keyname
    ssh-keygen -t rsa -b 4096 -C "guthrie.armstrong@gmail.com"
    eval "$(ssh-agent -s)"
    ssh-add "$HOME/.ssh/id_rsa"
fi

# Configure git
source "$HOME/dotfiles/git/config.sh"

# Authenticate with GitHub
if ssh -T git@github.com
then
    echo "Uploading public key to GitHub..."
    myjson='{"title":"'"$keyname"'","key":"'"$(cat $HOME/.ssh/id_rsa.pub)"'"}'
    eval "curl -u gmarmstrong --data '$myjson' https://api.github.com/user/keys"
fi

# Install base16
if ! [ -e "$HOME/.local/share/base16-shell" ]
then
    git clone https://github.com/chriskempson/base16-shell.git "$HOME/.local/share/base16-shell"
fi

# Fetch passwords
if ! [ -e "$HOME/.local/share/password-store" ]
then
    git clone git@github.com:gmarmstrong/passwords.git "$HOME/.local/share/password-store"
fi

# Install clustergit
if ! [ -e "$HOME/.local/bin/clustergit" ]
then
    curl -fLo "$HOME/.local/bin/clustergit" "https://raw.githubusercontent.com/mnagel/clustergit/master/clustergit"
fi

# Install vim-plug
if ! [ -e "$HOME/.local/share/vim/autoload/plug.vim" ]
then
    curl -fLo "$HOME/.local/share/vim/autoload/plug.vim" "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
fi

# Install Vim plugins
vim +qall
vim +PlugInstall +qall

# Update TeX Live
tlmgr update --self
tlmgr update --all
