#!/bin/bash

# Check for debug flag
debug=false
while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
        -d|--debug)
            debug=true
            ;;
        *) # Do something with extra options
            echo "Unknown option '$key'"
            ;;
    esac
    shift # Shift after checking all cases to get the next option
done
source ~/dotfiles/scripts/newdebian-debug

# Test Debian
if ! [ -f "/etc/debian_version" ];
then
    echo "Operating system not Debian, aborting."
    exit 1
fi

# Test connection
pingfunc() { eval "$ping -c 1 google.com"; }
if ! pingfunc; then
    echo "Internet connection failed, aborting."
    exit 1
fi

# Set up sudo
export user=$(whoami)
su root -c "$aptget -y install sudo"
su root -c "adduser $user sudo"
