#!/bin/bash

# Check operating system
echo "Verifying operating system..."
if uname | grep -q Darwin;
then
    echo "Congrats on the new Mac! 😃"
else
    echo "ERROR: Operating system is not macOS. Aborting."
    exit 1
fi

# Check Internet connection
if ! ping -c 1 google.com >& /dev/null;
then
    echo "ERROR: Internet connection failed. Aborting."
    exit 1
else
    echo "Internet connection successful."
fi

# Disable the "Last login" message
if ! [ -f ~/.hushlogin ]
then
    echo "Disabling the \"Last login\" message."
    touch ~/.hushlogin
fi

# Collect GitHub information and configure Git
if ! git config user.email >& /dev/null
then
    read -p "Enter email used for GitHub: " gh_email
    git config --global user.name "$github_username"
    read -p "Enter GitHub username: " github_username
    git config --global user.email "$gh_email"
fi

# Generate key and upload to GitHub
mkdir ~/.ssh
if ! [ -e ~/.ssh/id_rsa ] # Check that no key exists
then
    echo "Generating key."
    read -p "Enter a unique name for your GitHub key: " github_keyname
    echo "Generating SSH key."
    ssh-keygen -q -t rsa -b 4096 -C "$gh_email"
    eval "$(ssh-agent -s)" &> /dev/null
    ssh-add "~/.ssh/id_rsa" &> /dev/null
    myjson='{"title":"'"$github_keyname"'","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}'
    echo "Uploading public key to GitHub."
    eval "curl --silent -u $github_username --data '$myjson' https://api.github.com/user/keys"
else
    echo "Key already exists."
fi

# Clone scripts repository
if ! [ -e ~/scripts ]
then
    echo "Downloading scripts."
    git clone git@github.com:gmarmstrong/scripts.git
fi

# Clone applescripts repository
if ! [ -e ~/applescripts ]
then
    echo "Downloading AppleScripts."
    git clone git@github.com:gmarmstrong/applescripts.git
fi

# Install Homebrew
if test ! $(which brew)
then
    echo "Installing Homebrew."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    echo "Homebrew already installed."
fi

# Install mas
if ! command -v mas >& /dev/null
then
    brew install mas
fi

# Sign in to Mac App Store
if [ -z $(mas account) ]; then
    echo "Signing in to the Mac App Store"
    read -p "Enter email used for Mac App Store: " mas_email
    mas signin "$mas_email"
fi

# Symlink dotfiles
echo "Symlinking dotfiles."
ln -s ~/dotfiles/Brewfile ~/Brewfile >& /dev/null
ln -s ~/dotfiles/zshrc ~/.zshrc >& /dev/null
ln -s ~/dotfiles/vimrc ~/.vimrc >& /dev/null
ln -s ~/dotfiles/zshenv ~/.zshenv >& /dev/null
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global >& /dev/null

# Download all programs
echo "Downloading and updating programs."
brew update
brew upgrade
brew bundle --file="$HOME/Brewfile"

# Download OpenVPN configuration files (for Private Internet Access)
if [ -e "/Applications/Tunnelblick.app" ]
then
    echo "Downloading OpenVPN configuration files."
    open "/Applications/Tunnelblick.app"
    wget https://www.privateinternetaccess.com/openvpn/openvpn.zip
    unzip openvpn.zip -d openvpn
    open openvpn/*
    rm openvpn.zip
    # TODO Automate this. Watch how Tunnelblick does it (each configuration gets its own subdirectory.)
    echo "Opened the configuration files for manual installation."
    echo "You can delete ~/openvpn/ when you're done."
fi

# Use pure prompt
mkdir .zfunctions >& /dev/null
if [ ! -e "$HOME/.zfunctions/pure_prompt_setup" ]; then
    wget https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh -O "$HOME/.zfunctions/prompt_pure_setup"
fi
if [ ! -e "$HOME/.zfunctions/async" ]; then
    wget https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh -O "$HOME/.zfunctions/async"
fi

# Symlink iCloud Drive
if ! [ -d ~/iCloud ]
then
    echo "Creating iCloud Drive shortcut."
    ln -s ~/Library/Mobile\ Documents/com~apple~CloudDocs/Personal ~/iCloud
fi

# Point Git to global exclusion file
git config --global core.excludesfile ~/.gitignore_global

# Install vim-plug
if ! [ -e ~/.vim/autoload/plug.vim ]
then
    echo "Installing vim-plug."
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install Vim plugins
echo "Installing Vim plugins."
vim +qall
vim +PlugInstall +qall

# Prevent buyer's remorse, stage two
echo "All done. Enjoy! 😊"
