#!/bin/bash

echo "This script isn't done yet!"
exit 0

. "$HOME/dotfiles/scripts/functions.sh"

git_setup
symlink_agnostic_dotfiles
test $operating_system == Darwin && symlink_darwin_dotfiles
test $operating_system == Linux && symlink_linux_dotfiles
setup_package_manager
# TODO Install VirtualBox guest additions
antigen_setup
install_pip
generate_key
github_auth
vim_setup
test $operating_system = Darwin && setup_vpn

echo "All done! You should log out and log back in now."
