#!/bin/bash

echo "This script isn't done yet!"
exit 0

. "$HOME/dotfiles/scripts/functions.sh"

test_internet_connection
check_user_privileges
git_setup
symlink_agnostic_dotfiles
test $operating_system == Darwin && symlink_darwin_dotfiles
test $operating_system == Linux && symlink_linux_dotfiles
setup_package_manager

# TODO Install VirtualBox guest additions
# TODO Install pip and pip3

generate_key
github_auth

# Install Vim, vim-plug, and Vim plugins
curl -fL -o $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +qall
vim +PlugInstall +qall

# Install pure prompt
mkdir "$HOME/.zfunctions"
if [ ! -e "$HOME/.zfunctions/pure_prompt_setup" ] || [ ! -e "$HOME/.zfunctions/async" ]
then
    wget https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh -O "$HOME/.zfunctions/prompt_pure_setup"
    wget https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh -O "$HOME/.zfunctions/async"
fi

# Finish setup
echo "All done! You should log out and log back in now."
