#!/bin/bash

echo "This script isn't done yet!"
exit 0

. "$HOME/dotfiles/scripts/functions.sh"

# TODO Detect remote status with $SSH_CLIENT environment variable

test_internet_connection
check_user_privileges
