#!/bin/bash

## To install, enter:
#   cd "$HOME"
#   wget --no-check-certificate https://github.com/gmarmstrong/dotfiles/blob/master/scripts/setup
#   wget --no-check-certificate https://github.com/gmarmstrong/dotfiles/blob/master/scripts/post-setup
#   ./setup
#   newgrp sudo
#   newgrp -
#   ./post-setup
#   logout

echo "This script isn't done yet!"
exit 0

. "$HOME/dotfiles/scripts/functions.sh"

# TODO Always link and tic .iterm2_definition if $SSH_CLIENT is set or if Darwin
# before setting TERM (i.e., before sourcing zshrc)

test_internet_connection
check_user_privileges
