#!/usr/bin/env zsh

# file management aliases
alias tree="tree -a -I '__pycache__|*.pyc|target|.git|.sass-cache'"
alias ls="LC_COLLATE=C ls --color=auto -FH -w 80"
alias ll="LC_COLLATE=C ls --color=auto -FHA -w 80"
alias l="LC_COLLATE=C ls --color=auto -FHAlh -w 80"
alias space="find -maxdepth 1 -exec du -sh "{}" \; | sort -h"
alias suspace="sudo find -maxdepth 1 -exec du -sh "{}" \; | sort -h"

# SSH aliases
alias nike='ssh -x gma@nike.cs.uga.edu'
alias nikex='ssh -Y gma@nike.cs.uga.edu'

# general aliases
alias sxiv="sxiv -b -a"
alias zathura="zathura --fork"

# neovim aliases
command -v nvim >/dev/null 2>&1 && alias vim="nvim" && alias vi="nvim"

# backup
alias backup="sudo rsync --verbose --delete-excluded -aAXv --exclude={'/home/*/.cache/*','/home/*/nextcloud','/home/*/.local/share/Steam','/home/*/.local/share/Trash/*'} /home /run/media/$USER/ca3036f2-022d-4b6e-bb03-ed762403fd3b"
